"""
data.py — Static curated databases that power the AutoEarner system.

These require NO API keys and are always available:
  • AFFILIATE_PROGRAMS  — best affiliate programs for developer content
  • BUG_BOUNTY_PLATFORMS — active bug bounty platforms with payout ranges
  • STATIC_OPPORTUNITIES — proven $50/day strategies (always shown as fallback)
  • CONTENT_TEMPLATES    — fill-in-the-blank content blueprints
"""

from datetime import datetime

# ── Affiliate Programs (curated, highest commissions for dev content) ─────────
AFFILIATE_PROGRAMS = [
    # ── Hosting (highest payouts) ─────────────────────────────────────────
    {
        "name": "Hostinger", "category": "Hosting",
        "commission": "Up to 60% per sale", "avg_payout": "$65",
        "cookie_days": 30, "tier": "S",
        "why": "Massive conversion rate, beginner audience, $65+ per sale",
        "signup_url": "https://www.hostinger.com/affiliates",
        "content_angle": "Write 'How to deploy Node.js / React app on Hostinger'",
        "monthly_if_3_sales": "$195",
    },
    {
        "name": "WP Engine", "category": "Hosting",
        "commission": "$200 per referral", "avg_payout": "$200",
        "cookie_days": 60, "tier": "S",
        "why": "Premium managed hosting, highest single payout",
        "signup_url": "https://wpengine.com/affiliates/",
        "content_angle": "Write 'Best managed WordPress hosting for developers'",
        "monthly_if_3_sales": "$600",
    },
    {
        "name": "Kinsta", "category": "Hosting",
        "commission": "Up to $500 + 10% recurring", "avg_payout": "$300",
        "cookie_days": 60, "tier": "S",
        "why": "Recurring 10% makes this compound over time",
        "signup_url": "https://kinsta.com/affiliates/",
        "content_angle": "Write 'Why we migrated from Heroku to Kinsta (and saved 40%)'",
        "monthly_if_3_sales": "$900+",
    },
    {
        "name": "Bluehost", "category": "Hosting",
        "commission": "$65 per sale", "avg_payout": "$65",
        "cookie_days": 90, "tier": "A",
        "why": "Huge brand recognition, easy conversions for beginners",
        "signup_url": "https://www.bluehost.com/affiliates",
        "content_angle": "Write 'How to host your first website for $2.95/month'",
        "monthly_if_3_sales": "$195",
    },
    # ── Cloud Platforms ──────────────────────────────────────────────────
    {
        "name": "Digital Ocean", "category": "Cloud",
        "commission": "$25 per signup", "avg_payout": "$25",
        "cookie_days": 30, "tier": "A",
        "why": "Extremely popular with developers, easy tutorial content",
        "signup_url": "https://www.digitalocean.com/referral-program",
        "content_angle": "Write 'Deploy your first Docker container on DigitalOcean in 10 min'",
        "monthly_if_3_sales": "$75",
    },
    {
        "name": "Vultr", "category": "Cloud",
        "commission": "$35 per signup + 10% for 12 mo", "avg_payout": "$70",
        "cookie_days": 30, "tier": "A",
        "why": "Developer-friendly, great for VPS tutorials",
        "signup_url": "https://www.vultr.com/promo/refer",
        "content_angle": "Write 'Vultr vs DigitalOcean: Which is better for Node.js?'",
        "monthly_if_3_sales": "$105",
    },
    # ── Dev Tools ────────────────────────────────────────────────────────
    {
        "name": "Semrush", "category": "SEO Tools",
        "commission": "$200 per sale + $10 per trial", "avg_payout": "$200",
        "cookie_days": 120, "tier": "S",
        "why": "Every blogger/SaaS needs SEO tools. $200 per sale is huge.",
        "signup_url": "https://www.semrush.com/partner/",
        "content_angle": "Write 'How to do SEO for your developer blog (tools I use)'",
        "monthly_if_3_sales": "$600",
    },
    {
        "name": "Vercel Pro", "category": "Dev Tools",
        "commission": "$100 per Pro referral", "avg_payout": "$100",
        "cookie_days": 30, "tier": "A",
        "why": "Every React developer uses or knows Vercel",
        "signup_url": "https://vercel.com/partners",
        "content_angle": "Write 'Why I moved all my projects to Vercel (and how)'",
        "monthly_if_3_sales": "$300",
    },
    # ── Education ────────────────────────────────────────────────────────
    {
        "name": "Coursera", "category": "Education",
        "commission": "45% of course price", "avg_payout": "$22-45",
        "cookie_days": 30, "tier": "A",
        "why": "High conversion for tech learning, big audience",
        "signup_url": "https://about.coursera.org/affiliates/",
        "content_angle": "Write 'Best courses to learn [React/Node/Python] in 2025'",
        "monthly_if_3_sales": "$90-135",
    },
    {
        "name": "Udemy", "category": "Education",
        "commission": "15-20% per course", "avg_payout": "$2-30",
        "cookie_days": 7, "tier": "B",
        "why": "Volume play — millions of buyers, easy to link",
        "signup_url": "https://www.udemy.com/affiliate/",
        "content_angle": "Write 'Top 10 Udemy courses for full-stack developers'",
        "monthly_if_3_sales": "$6-90",
    },
    # ── Business Tools ───────────────────────────────────────────────────
    {
        "name": "Shopify", "category": "E-Commerce",
        "commission": "Up to $150 per referral", "avg_payout": "$150",
        "cookie_days": 30, "tier": "A",
        "why": "Every small business wants an online store",
        "signup_url": "https://www.shopify.com/affiliates",
        "content_angle": "Write 'How to build a Shopify app as a developer and earn recurring income'",
        "monthly_if_3_sales": "$450",
    },
    {
        "name": "ConvertKit", "category": "Email Marketing",
        "commission": "30% recurring for 24 months", "avg_payout": "$9-30/mo",
        "cookie_days": 30, "tier": "A",
        "why": "Recurring commissions — earn every month from one referral",
        "signup_url": "https://convertkit.com/affiliate",
        "content_angle": "Write 'How I built my developer newsletter with ConvertKit'",
        "monthly_if_3_sales": "$27-90/mo recurring",
    },
    # ── VPN / Security ───────────────────────────────────────────────────
    {
        "name": "NordVPN", "category": "VPN",
        "commission": "40% per sale + 30% renewal", "avg_payout": "$40-140",
        "cookie_days": 30, "tier": "A",
        "why": "Easy to embed in any security/privacy tutorial",
        "signup_url": "https://affiliates.nordvpn.com/",
        "content_angle": "Write 'Developer security checklist: Why you need a VPN in 2025'",
        "monthly_if_3_sales": "$120-420",
    },
    # ── Crypto/Finance ───────────────────────────────────────────────────
    {
        "name": "Coinbase", "category": "Crypto",
        "commission": "50% of trading fees for 3 mo", "avg_payout": "$10-50",
        "cookie_days": 30, "tier": "B",
        "why": "High interest in crypto, easy to embed in finance content",
        "signup_url": "https://www.coinbase.com/affiliates",
        "content_angle": "Write 'How to automate crypto investing with Python'",
        "monthly_if_3_sales": "$30-150",
    },
]

# ── Bug Bounty Platforms ──────────────────────────────────────────────────────
BUG_BOUNTY_PLATFORMS = [
    {
        "name": "HackerOne",
        "url": "https://hackerone.com/opportunities",
        "avg_payout_low": 50, "avg_payout_high": 500,
        "programs": 2000,
        "beginner_friendly": True,
        "min_severity": "Low",
        "description": "World's largest bug bounty platform. Many programs accept beginners. Filter by 'Managed' programs for highest payouts.",
        "getting_started": "https://www.hackerone.com/resources/hackerone/the-beginners-guide-to-bug-bounty-hunting",
        "top_programs": ["Shopify ($500+)", "Twitter ($140+)", "GitHub ($617+)", "Spotify ($250+)"],
        "checklist": [
            "Create HackerOne account (free)",
            "Complete your profile and skills",
            "Start with programs that have 'Managed' label",
            "Focus on IDOR, XSS, and auth bypass vulnerabilities first",
            "Read the program's scope carefully before testing",
            "Use Burp Suite Community (free) for testing",
        ],
    },
    {
        "name": "Bugcrowd",
        "url": "https://bugcrowd.com/programs",
        "avg_payout_low": 100, "avg_payout_high": 400,
        "programs": 1200,
        "beginner_friendly": True,
        "min_severity": "Low",
        "description": "Excellent platform for beginners. Many public programs. Good community and learning resources.",
        "getting_started": "https://www.bugcrowd.com/blog/getting-started-bug-bounty-hunter-beginner/",
        "top_programs": ["Tesla ($100+)", "Mastercard ($500+)", "Cisco ($300+)"],
        "checklist": [
            "Sign up at bugcrowd.com",
            "Join their Discord for tips from experienced hunters",
            "Start with Tesla or Atlassian programs (developer-friendly)",
            "Look for API security issues — your backend knowledge is an advantage",
        ],
    },
    {
        "name": "Intigriti",
        "url": "https://intigriti.com",
        "avg_payout_low": 200, "avg_payout_high": 1000,
        "programs": 500,
        "beginner_friendly": False,
        "min_severity": "Medium",
        "description": "European platform with higher payouts. More competitive but less crowded than HackerOne.",
        "getting_started": "https://blog.intigriti.com/category/hackademy/",
        "top_programs": ["Various EU companies ($200-2000)"],
        "checklist": [
            "Requires some experience first — start with HackerOne",
            "Focus on business logic vulnerabilities",
            "European programs often pay faster",
        ],
    },
    {
        "name": "Open Bug Bounty",
        "url": "https://www.openbugbounty.org",
        "avg_payout_low": 0, "avg_payout_high": 200,
        "programs": 5000,
        "beginner_friendly": True,
        "min_severity": "Low",
        "description": "Free, responsible disclosure platform. Great for practice and building reputation. Some companies pay voluntarily.",
        "getting_started": "https://www.openbugbounty.org/about/",
        "top_programs": ["Thousands of sites accepting reports"],
        "checklist": [
            "Best for practice — not all programs pay",
            "Great for building your public CVE portfolio",
            "Focus on XSS vulnerabilities — most common and accepted",
        ],
    },
]

# ── Static Earning Strategies (shown when API key not set) ────────────────────
STATIC_DAILY_STRATEGIES = [
    {
        "id": "affiliate_content",
        "title": "Daily Article + Affiliate Links",
        "category": "Content",
        "earning_model": "Affiliate Commission",
        "time_per_day": "2-3 hours",
        "daily_target": "$50-150",
        "timeline_to_target": "30-60 days",
        "difficulty": "Easy",
        "description": "Write 1 technical tutorial per day on a trending topic. Add affiliate links. Publish on Dev.to, Hashnode, and Medium simultaneously. Traffic builds over 30 days.",
        "why_works": "Dev.to has 1M+ developer readers. A good article gets 500-5,000 views. Even 1% click-through on a $65 commission = $3.25 per article. Stack 20 articles = $65/day passively.",
        "steps": [
            "Pick topic using Google Trends (search '[tech] tutorial')",
            "Write 800-word article (use AI to accelerate)",
            "Add 2-3 natural affiliate links (Digital Ocean, Hostinger, tools you mention)",
            "Publish on Dev.to + Hashnode + Medium simultaneously",
            "Share on LinkedIn + Twitter with a hook",
            "Repeat for 30 days — articles compound in traffic",
        ],
        "income_example": "20 articles × 2,000 avg views × 1% CTR × $65 avg commission = $26/day growing to $65+/day at 50 articles",
        "affiliate_recommendations": ["Hostinger", "Digital Ocean", "Semrush", "Vercel Pro"],
        "platforms": ["Dev.to", "Hashnode", "Medium", "LinkedIn"],
        "tools": ["AI writing assistant", "Canva for thumbnails", "Hemingway Editor"],
    },
    {
        "id": "bug_bounty",
        "title": "Bug Bounty Hunting",
        "category": "Security",
        "earning_model": "Vulnerability Rewards",
        "time_per_day": "3-4 hours",
        "daily_target": "$50-500",
        "timeline_to_target": "1-4 weeks",
        "difficulty": "Medium",
        "description": "Find security vulnerabilities in websites and apps. Report them to companies who pay rewards. As a developer, you already understand how apps work — huge advantage.",
        "why_works": "Companies legally pay hackers to find bugs before bad actors do. Even 'Low' severity bugs pay $50-200. One Medium/High bug per week = $200-1000.",
        "steps": [
            "Create HackerOne account (free, takes 5 minutes)",
            "Install Burp Suite Community (free web security tool)",
            "Pick a beginner-friendly program (Shopify, GitHub, Twitter)",
            "Read their scope carefully — test ONLY what's allowed",
            "Test for IDOR vulnerabilities (most common for beginners)",
            "Submit detailed, reproducible report",
        ],
        "income_example": "1 Low bug/day × $100 avg = $700/week. 1 Medium bug/week × $500 avg = $2,000/month",
        "affiliate_recommendations": [],
        "platforms": ["HackerOne", "Bugcrowd", "Intigriti"],
        "tools": ["Burp Suite (free)", "OWASP ZAP (free)", "Postman", "Browser DevTools"],
    },
    {
        "id": "template_sales",
        "title": "Sell Code Templates on Gumroad",
        "category": "Digital Products",
        "earning_model": "Product Sales",
        "time_per_day": "1-2 hours (after initial setup)",
        "daily_target": "$50-200",
        "timeline_to_target": "7-14 days",
        "difficulty": "Easy",
        "description": "Build once, sell forever. Create React templates, Next.js starters, REST API boilerplates, or Figma-to-code components. Sell on Gumroad for $9-49 each.",
        "why_works": "Developers will pay $15-49 to save 4 hours of setup. If your template saves time, they buy without thinking. Zero transaction cost after creation.",
        "steps": [
            "Build a clean, well-documented starter template (Next.js + Auth + DB + Stripe is gold)",
            "Record a 2-minute demo video",
            "Create Gumroad account (free, they take 10%)",
            "List for $19-29 with 'Preview' of the code quality",
            "Post on r/webdev, r/reactjs, Indie Hackers with value-first post",
            "Reinvest: build 1 new template per week",
        ],
        "income_example": "3 templates × 2 sales/day × $19 = $114/day passive once ranked on Gumroad",
        "affiliate_recommendations": ["Vercel Pro", "Supabase"],
        "platforms": ["Gumroad", "LemonSqueezy", "CodeCanyon", "GitHub Marketplace"],
        "tools": ["VS Code", "GitHub", "Loom (demo video)"],
    },
    {
        "id": "newsletter_affiliate",
        "title": "Technical Newsletter + Affiliates",
        "category": "Newsletter",
        "earning_model": "Affiliate + Paid Subscriptions",
        "time_per_day": "1-2 hours",
        "daily_target": "$50-150",
        "timeline_to_target": "60-90 days",
        "difficulty": "Easy",
        "description": "Send a weekly technical newsletter to developers. Monetize through affiliate links and paid subscriptions. Email has 40% open rates vs 5% on social media.",
        "why_works": "150 paid subscribers at $10/month = $1,500/month ($50/day). Plus affiliate revenue on top. Email list is YOUR asset — not dependent on any algorithm.",
        "steps": [
            "Start on Substack (free, takes 10% of revenue)",
            "Choose a niche: AI tools, React tips, security, career advice",
            "Write 1 newsletter per week with 3-5 valuable tips",
            "Add 1-2 relevant affiliate links naturally in each issue",
            "Grow by posting newsletter content on LinkedIn/Twitter",
            "After 100 subscribers, launch $10/month paid tier with bonus content",
        ],
        "income_example": "200 free subscribers + affiliate clicks = $50/mo. 150 paid subscribers = $1,500/mo = $50/day",
        "affiliate_recommendations": ["ConvertKit", "Semrush", "Coursera"],
        "platforms": ["Substack", "Beehiiv", "ConvertKit"],
        "tools": ["Substack", "Canva", "Grammarly"],
    },
]

# ── Content Blueprint Templates ────────────────────────────────────────────────
CONTENT_BLUEPRINTS = [
    {
        "type": "Tutorial",
        "title_formula": "How to [do specific thing] with [technology] in [time]",
        "example": "How to Deploy a Full-Stack App on Digital Ocean in 10 Minutes",
        "structure": ["Problem hook", "What you'll build", "Prerequisites", "Step-by-step with code", "Common errors", "Next steps + affiliate recommendation"],
        "best_affiliate": "Digital Ocean, Hostinger, Vercel",
        "avg_views": "2,000-10,000",
    },
    {
        "type": "Comparison",
        "title_formula": "[Tool A] vs [Tool B]: Which is better for [use case] in [year]",
        "example": "Vercel vs Netlify vs DigitalOcean: Which is Best for React Apps in 2025",
        "structure": ["Quick answer (for SEO)", "Detailed comparison table", "Pros and cons each", "Which to choose based on use case", "Our recommendation (with affiliate link)"],
        "best_affiliate": "Vercel, Digital Ocean, Hostinger",
        "avg_views": "5,000-20,000",
    },
    {
        "type": "List Article",
        "title_formula": "[Number] Best [tools/resources/tips] for [audience] in [year]",
        "example": "10 Essential Tools Every Node.js Developer Should Know in 2025",
        "structure": ["Why this list matters", "Each tool: what it does + why it's on the list + affiliate link", "Summary table", "Your top 3 picks"],
        "best_affiliate": "Multiple tools in one article — highest affiliate potential",
        "avg_views": "3,000-15,000",
    },
]
